//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GL_Two.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_OBJECTVIEW                  102
#define ID_INDICATOR_TIME               103
#define IDR_MAINFRAME                   128
#define IDR_GL_TWOTYPE                  129
#define IDD_CONSTRUCTION                130
#define ID_INDICATOR_FOV                130
#define IDB_AXIS                        131
#define ID_INDICATOR_LOOK_FROM          131
#define IDI_ICON1                       132
#define ID_INDICATOR_LOOK_AT            132
#define IDD_VIEW                        133
#define ID_INDICATOR_CLIP               133
#define IDD_POLYGON                     134
#define ID_INDICATOR_VIEW_DIRTY         134
#define IDD_COMP_DLG                    135
#define IDR_GL_IMGTYPE                  135
#define IDB_BITMAP1                     136
#define IDD_SELECTION                   138
#define IDD_REPEAT_DIALOG               139
#define IDC_SCALE                       1000
#define IDC_WIDTH                       1001
#define IDC_HEIGHT                      1002
#define IDC_DEPTH                       1003
#define IDC_IN_RADIUS                   1004
#define IDC_OUT_RADIUS                  1005
#define IDC_RADIUS                      1006
#define IDC_TRANSX                      1007
#define IDC_TRANSY                      1008
#define IDC_TRANSZ                      1009
#define IDC_STATIC_RADIUS               1010
#define IDC_STATIC_SIZE                 1011
#define IDC_STATIC_WIDTH                1012
#define IDC_STATIC_HEIGHT               1013
#define IDC_STATIC_DEPTH                1014
#define IDC_STATIC_IN_RADIUS            1015
#define IDC_STATIC_OUT_RADIUS           1016
#define IDC_ROTATE_X                    1017
#define IDC_ROTATE_Y                    1018
#define IDC_ROTATE_Z                    1019
#define IDC_EYEX                        1020
#define IDC_EYEY                        1021
#define IDC_EYEZ                        1022
#define IDC_CENTERX                     1023
#define IDC_CENTERY                     1024
#define IDC_CENTERZ                     1025
#define IDC_UPX                         1026
#define IDC_UPY                         1027
#define IDC_UPZ                         1028
#define IDC_FOV                         1029
#define IDC_NEAR_CLIP                   1030
#define IDC_FAR_CLIP                    1031
#define IDC_STATIC_TRANSX               1032
#define IDC_STATIC_TRANSY               1033
#define IDC_STATIC_TRANSZ               1034
#define IDC_POINTS                      1035
#define IDC_NEXT                        1037
#define IDC_PREVIOUS                    1038
#define IDC_X                           1039
#define IDC_Y                           1040
#define IDC_Z                           1041
#define IDC_DOUBLEX                     1042
#define IDC_DOUBLEY                     1043
#define IDC_DOUBLEZ                     1044
#define IDC_EDIT5                       1045
#define IDC_CONVEX                      1046
#define IDC_OBJ_LIST                    1047
#define IDC_TRANS_X                     1048
#define IDC_TRANS_Y                     1049
#define IDC_TRANS_Z                     1050
#define IDC_SCALE_X                     1053
#define IDC_SCALE_Z                     1055
#define IDC_CHECK1                      1056
#define IDC_IMPORT                      1056
#define IDC_CLOSED_CHK                  1056
#define IDC_BUTTON1                     1057
#define IDC_COPY                        1057
#define IDC_SCALE_Y                     1058
#define IDC_TYPE_LIST                   1060
#define IDC_EDIT_NAME                   1061
#define IDC_COLOR                       1062
#define IDC_HIT_LIST                    1063
#define IDC_OBJECT_TREE                 1063
#define IDC_DELETE_BUTTON               1064
#define IDC_EDIT_DESCRIPTOR             1065
#define IDC_COPY_BUTTON                 1065
#define IDC_REPEAT_BTN                  1066
#define IDC_STATIC_COPIES               1067
#define IDC_STATIC_YOFF                 1068
#define IDC_STATIC_XOFF                 1069
#define IDC_STATIC_ZOFF                 1070
#define IDC_EDIT_XOFF                   1071
#define IDC_EDIT_COPIES                 1072
#define IDC_EDIT_YOFF                   1073
#define IDC_EDIT_ZOFF                   1074
#define IDC_STATIC_ROTATEX              1075
#define IDC_STATIC_ROTATEY              1076
#define IDC_STATIC_ROTATEZ              1077
#define IDC_SINGLE_COLOR                1078
#define IDC_IS_A_CLIP                   1082
#define IDC_DEFAULT_CHK                 1083
#define ID_PRIMITIVES_POINTS            32771
#define ID_PRIMITIVES_LINES             32772
#define ID_PRIMITIVES_POLYGONS          32773
#define ID_SOLIDS_BOX                   32774
#define ID_SOLIDS_CUBE                  32775
#define ID_SOLIDS_CONE                  32776
#define ID_SOLIDS_CYLINDER              32777
#define ID_SOLIDS_DODECAHEDRON          32778
#define ID_SOLIDS_ICOSAHEDRON           32779
#define ID_SOLIDS_OCTAHEDRON            32780
#define ID_SOLIDS_TETRAHEDRON           32781
#define ID_SOLIDS_TEAPOT                32782
#define ID_SOLIDS_TORUS                 32783
#define ID_SOLIDS_SPHERE                32784
#define ID_VIEW_SETTINGS                32785
#define ID_EDIT_CLEARALL                32786
#define ID_OBJECTS_NEW                  32787
#define ID_OBJECTS_LIST                 32788
#define ID_OBJECTS_FROMFILE             32789
#define ID_SOLIDS_DISK                  32790
#define ID_HELP_IMPEMENTATIONINFO       32791
#define ID_HELP_IMPLEMENTATIONINFO      32792
#define ID_VIEW_WIREFRAME               32793
#define ID_VIEW_BLACKANDWHITE           32794
#define ID_VIEW_CULLFACES               32795
#define ID_VIEW_CAP                     32796

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         1084
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
